### ISSUE TITLE
checkpoint from texture refinement stage is a symbolic link to itself

### ISSUE THREAD

**Issue by markkurt** [DSaurus/threestudio-dreamcraft3D#11]
`ls -al outputs/dreamcraft3d-texture/a_mans_face\,_frontview\@20231227-201844/ckpts/last.ckpt`

`lrwxrwxrwx 1 root root 101 Dec 27 20:46 outputs/dreamcraft3d-texture/a_mans_face,_frontview@20231227-201844/ckpts/last.ckpt -> /root/threestudio/outputs/dreamcraft3d-texture/a_mans_face,_frontview@20231227-201844/ckpts/last.ckpt`

(the symbolic link points to itself)

When using that checkpoint for model export the error reported is: `OSError: [Errno 40] Too many levels of symbolic links: 'outputs/dreamcraft3d-texture/a_mans_face,_frontview@20231227-201844/ckpts/last.ckpt'`

**Comment by markkurt** [comment]
changing the last line of the texture config: https://github.com/DSaurus/threestudio-dreamcraft3D/blob/master/configs/dreamcraft3d-texture.yaml#L148 to match the last line of the other configs worked to fix this issue for me: https://github.com/DSaurus/threestudio-dreamcraft3D/blob/master/configs/dreamcraft3d-geometry.yaml#L132

i.e., changing:
`every_n_train_steps: 0` to `every_n_train_steps: ${trainer.max_steps}`

**Comment by DSaurus** [comment]
Hi, @markkurt ,

Thank you for finding this bug. I have fixed it in commit 256c9a7.

**Comment by markkurt** [comment]
thanks!
